### ISSUE TITLE
[graviAURA]:  Tree distribution of BADGER from bribe processor not reflecting in ROI of app

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/bug-reports#10]
Unsure if rewards were distributed.

4 hours ago this TX sent 1928 BADGER from the tree earned from graviAURA bribs:
https://etherscan.io/tx/0x1e3e7c71012d36e936b768a37e9784125a00f205a22bd808f045968a506bb1ce

It is stiil not reflecting in the ROI on the UI:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/11885129/184633677-5a24c61f-1222-446b-aaa8-16b5abea0ed7.png">

Ninja is not showing any details about harvests or tree distributions:
https://badger-ninja.vercel.app/vault/ethereum/0xBA485b556399123261a5F9c95d413B4f93107407

The yields on graviAURA have now been way too low for over a week.  This is a serious issue for user experience.  It would be nice to get our bribes paid and reflected ASAP.

There are also problems with processing non-badger bribes that I will work with the multisig on, this ticket is about making sure what is sent to the tree is paid out to users and reflected.

Prio: **High**

**Comment by Tritium-VLK** [comment]
Is anyone looking at this?  What is the process of requesting attention on a user facing problem?

**Comment by Tritium-VLK** [comment]
Note that graviAURA was also emitted to the tree in this TX https://etherscan.io/tx/0x33eb98453cda3e19da1edaac2b3fd21b223d79d0ccf02e8b28e6b0faa0cfd647

based on testing recorded in lines 15-20 in this sheet, these emissions were also not paid out to HODLers at the turn of the cycle:

https://docs.google.com/spreadsheets/d/1GoEuCU-0oFHfAMuhg7WLrHCapHcwzDd5QjPmiQVjDO4/edit#gid=0

**Comment by dapp-whisperer** [comment]
Copying this from a thread regarding missing BADGER from the graviAURA bribe distribution:

This contract is not using the harvest distributor, which is why the badger wasn't processed

```
{
  badgerTreeDistributions(where: {blockNumber: 15344809}) {
    blockNumber
    timestamp
    amount
    token {
      name
    }
    sett {
      name
    }
  }
}

{
  "data": {
    "badgerTreeDistributions": []
  }
}
```

It's emitting directly from the strategy
0x3c0989eF27e3e3fAb87a2d7C38B35880C90E63b5

https://etherscan.io/address/0x0d724e8aee6f73b35a596c8c947c92c75eac7818#code#F1#L2096
This should use the HarvestDistribution contract

https://etherscan.io/tx/0x33eb98453cda3e19da1edaac2b3fd21b223d79d0ccf02e8b28e6b0faa0cfd647#eventlog
Example distribution from the graviaura contract using the Harvest Distributor properly 

We need the contract updated to process this correctly so we don't need spaghetti code on the web2 side and we can run a custom cycle to distribute the badger this time

**Comment by dapp-whisperer** [comment]
**The Fix**

Upgrade the contract here: 
https://etherscan.io/address/0x0d724e8aee6f73b35a596c8c947c92c75eac7818#code#F1#L2096

**Comment by Tritium-VLK** [comment]
graviAURA rewards have now paid out on the tree.  Still not reflecting in the UI.

**Comment by Tritium-VLK** [comment]
This issue is still not resolved. The UI is showing 26%. Based on a distribution of around 7k worth of badger to around 100k of HODLer gravi yields should be closer to 180%. Users are asking questions.

Can we please have an update about what the problem is, what changed yesterday, what work is ongoing and when the next update will come out so I can share it with graviAURA depositors?

**Comment by dapp-whisperer** [comment]
the latest from yesterday that I'm aware of:

@axejintao has been personally investigating UI side with high priority

@sajanrajdev will be leading the SC change, unsure of priority or timeline

@mitche50 may have more info as well

**Comment by dapp-whisperer** [comment]
Saj has informed any SC changes would interfere with the change made here: https://github.com/Badger-Finance/vested-aura/pull/12

@Tritium-VLK can you help clarify what should happen from product side?

**Comment by Tritium-VLK** [comment]
@dapp-whisperer still taking to @GalloDaSballo about the strategy upgrade that is the other side of what Saj is saying (sending badger to the treasury instead of the tree).  

That is part of this project  https://github.com/Badger-Finance/Badger-Project-Planning/issues/75  that has evolved a bit into being a generalized approach to bribe handling for DAOs so we don't need to upgrade again based on this miro:

https://miro.com/app/board/uXjVPeicKQ0=/

In the end, on the backend side there are a few simple changes that make everything work better, create cleaner isolation between concerns, and both resolve most of these issues and create new opertunities to realize our fees and provide a good bribe solution for DAOs. 

Maybe You, Me, @sajanrajdev , @GalloDaSballo and perhaps @SHAKOTN should just on a short call to try to understand all of this and agree on a way forward.

**As it stands:**
The autovoter will no longer hunt badger bribes(https://github.com/Badger-Finance/aura-autovoter/issues/69).  That means that all badger earned by the autovoter is "property" of the treasury.  It is therefore no longer a user facing incident/problem if BADGER is not distributed, but it is kind of a mess if we send treasury badger to the tree without an event and have to reclaim it later.

The real "incident" level problem right now is more on the frontend/yield display side as graviAURA still looks like its seriously underperforming when it's actually over-performing.  Can we also get an update about that posted to this ticket at least once ever 24 hours, or can you link to the ticket where the work on investigating that is being documented?


I will write a new project ticket that includes all these details and maybe follows a format that is easier for people to read, then maybe we can have a 30 minute call and go through it together to clear up any questions/agree to an approach?

**Comment by okjintao** [comment]
```
[8/15/2022, 3:14:26 PM] 757.19 AURA ($2059.54)
[8/15/2022, 9:47:02 AM] 4449.48 graviAURA ($12619.00)
[8/11/2022, 3:05:57 PM] 544.96 AURA ($1482.28)
[8/7/2022, 2:38:53 PM] 1142.49 AURA ($3107.57)
[8/4/2022, 2:22:19 PM] 622.37 BADGER ($2364.99)
[8/3/2022, 2:06:24 PM] 1035.20 AURA ($2815.74)
Total: $24449.13, Est. Yield: 24.95%
```

here is (without weighting math) what the API is seeing in terms of intputs

**Comment by okjintao** [comment]
It seems no distributions are logged in that block for the vault or in the sbugraph.

**Comment by dapp-whisperer** [comment]
## Solution found, under development
@Tritium-VLK 
We've decided the best path forward is a hacky patch to make the yield displayed match reality, on the FE side.

This is the simplest, fastest solution and doesn't require any SC work to create a fake event, for example.

I'm investigating why the situation arose in the first place.

**Comment by okjintao** [comment]
```
[8/15/2022, 3:14:26 PM] 757.19 AURA ($2059.54)
[8/15/2022, 9:47:02 AM] 4449.48 graviAURA ($12619.00)
[8/15/2022, 3:49:56 AM] 1928.77 BADGER ($7329.33)
[8/11/2022, 3:05:57 PM] 544.96 AURA ($1482.28)
[8/7/2022, 2:38:53 PM] 1142.49 AURA ($3107.57)
[8/4/2022, 2:22:19 PM] 622.37 BADGER ($2364.99)
[8/3/2022, 2:06:24 PM] 1035.20 AURA ($2815.74)
Vault Holdings: $2555192.21, Total Earned: $31778.46, Est. Yield: 32.42%
```

new inputs, out of date timings for the current round

**Comment by okjintao** [comment]
> This issue is still not resolved. The UI is showing 26%. Based on a distribution of around 7k worth of badger to around 100k of HODLer gravi yields should be closer to 180%. Users are asking questions.
> 
> Can we please have an update about what the problem is, what changed yesterday, what work is ongoing and when the next update will come out so I can share it with graviAURA depositors?

where is this 180% coming from - and where is this 100k coming from? 

the current tvl of the vault is 2m,

if the badger was earned over 2 weeks you are at around 8%, if it was 1 week then 16%

**Comment by Tritium-VLK** [comment]
> where is this 180% coming from - and where is this 100k coming from?
> 
> the current tvl of the vault is 2m,

The 100k comes from HODLer graviAURA.  Most of the graviAURA is in the balancer vault which is blacklisted from emissions.  Bribes only get paid out to people with graviAURA in their wallets.

https://daowatch.badger.guru/d/foWJO-k4k/graviaura-voting-dashboard?orgId=1&refresh=1m
<img width="712" alt="image" src="https://user-images.githubusercontent.com/11885129/185164836-c7d881a7-a9a2-4c87-a2f7-d6a1823b4c1d.png">

As you can see right now there is about 100k HODLer aura, and it has tended to range around there over the last weeks.

**Comment by Tritium-VLK** [comment]
This looks about right and will make users happy:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/11885129/185243619-32681710-b976-4d7c-b138-b53438759cbf.png">

Let's keep an eye on it following the next bribe payout.
