### ISSUE TITLE
bveCVX yields make no sense

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/bug-reports#13]
Last bribe round was just paid out:

We just paid another bribe round out.  Once again looking to glory tweet:

Right now the last 2 lines on the bveCVX bar show 28.54%: 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/11885129/186149429-22c2a821-f2ff-428e-af9a-87b89e36c6cd.png">
and  24.68%
<img width="210" alt="image" src="https://user-images.githubusercontent.com/11885129/186149487-42a4033a-39af-4418-b5fe-b8eeacfeb56f.png">

The yield on the site shows 60% (yesterday it showed 20ish but have no screenshot)
<img width="336" alt="image" src="https://user-images.githubusercontent.com/11885129/186149592-a784dbcc-aa54-40a8-9ce0-fa3ee8d2f544.png">

Tokens managed graph shows something different:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/11885129/186150150-2b42acab-073b-4b4d-ac41-b3db65084392.png">

When switching to APR the yield still shows 50+% which seems off.

Another round, no glory tweet...

**Comment by okjintao** [comment]
resolved

**Comment by okjintao** [comment]
# Summary

- bribes processor handled two rounds of incentives within 13 days, not an expected pattern here
- solution is to filter out events associated with bribe rounds specific to the voting strategy, graviaura will also get the same treatment

```
┌─────────┬─────────────┬──────────────┬───────────┬────────────────────┬──────────────┬─────────────────┬──────────┐
│ (index) │    date     │    amount    │   token   │        type        │    value     │     balance     │   apr    │
├─────────┼─────────────┼──────────────┼───────────┼────────────────────┼──────────────┼─────────────────┼──────────┤
│    0    │ '8/23/2022' │ '18,087.137' │ 'bveCVX'  │ 'TreeDistribution' │ '$97,489.67' │ '2,473,528.978' │ '17.79%' │
│    1    │ '8/23/2022' │ '8,273.444'  │ 'BADGER'  │ 'TreeDistribution' │ '$32,514.64' │ '2,473,528.978' │ '5.93%'  │
│    2    │ '8/22/2022' │ '4,261.975'  │ 'bcvxCRV' │ 'TreeDistribution' │ '$6,495.30'  │ '2,473,528.978' │ '1.22%'  │
│    3    │ '8/18/2022' │ '4,223.103'  │ 'bcvxCRV' │ 'TreeDistribution' │ '$7,413.01'  │ '2,473,528.978' │ '1.23%'  │
│    4    │ '8/14/2022' │  '4,285.53'  │ 'bcvxCRV' │ 'TreeDistribution' │ '$9,276.53'  │ '2,459,922.063' │ '1.26%'  │
│    5    │ '8/10/2022' │ '5,603.203'  │ 'bcvxCRV' │ 'TreeDistribution' │ '$10,319.90' │ '2,446,637.812' │ '1.48%'  │
└─────────┴─────────────┴──────────────┴───────────┴────────────────────┴──────────────┴─────────────────┴──────────┘
bveCVX: 28.92%
```
