### ISSUE TITLE
Badger Yields do not show earned swap fees nor account for badger fees taken

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/bug-reports#3]
- See https://discord.com/channels/743271185751474307/1001955496443527309/1001968681389146242 for feedback from the beta squad if swap fees are a blocker.

- Ensure that yields are shown less Badger fees taken.

![image](https://user-images.githubusercontent.com/11885129/181378619-43543e2a-8fa0-4c31-b919-145350bc3a61.png)
![image](https://user-images.githubusercontent.com/11885129/181378637-1f3f4aad-6dbf-4870-a6bf-b8b358c2475b.png)

**Comment by dapp-whisperer** [comment]
@axejintao @spadaboom perhaps relevant to yield display redesign?
