### ISSUE TITLE
The 40wbtc-40Digg-20graviAURA isnt accepting deposits

### ISSUE THREAD

**Issue by krypt0bi** [Badger-Finance/bug-reports#4]
On clicking the deposit for the vault, it throws up the error attached in screenshot. Have also attached console error. browser is chrome. using metamask wallet.
![sc](https://user-images.githubusercontent.com/76043315/181500208-378b3074-eabb-48c1-92ea-4e903ac8ec16.jpg)
![sc1](https://user-images.githubusercontent.com/76043315/181500249-dc1cd392-1cce-4215-8dad-4000c1f212ec.jpg)

Also report of not being able to deposit on any vault in the beta site, unless through chadger. wallet used is metamask on brave.

**Comment by Tritium-VLK** [comment]
I had the same problem on bauraBAL on a fresh wallet.  Asks once for approval, then fails with this error to launch mm on deposit.

**Comment by okjintao** [comment]
https://etherscan.io/tx/0xb929e6cef424c163e62227b4f0083970d8149e1d84f55adffd84d05fd1c9c5e5
deposited via UI with no changes

will test aura bal + digg vault as well

**Comment by okjintao** [comment]
https://etherscan.io/tx/0xb5d0f7cd4311cd3b006c7dd7a015fab84419e41bb78786f1b8a38c345ce1a857

tested withdraw via UI works

**Comment by okjintao** [comment]
https://etherscan.io/tx/0xc40ef667e4255282c13754f4ff6a1bc724c68b590c52868a26018fda43512f29

tested aurabal via UI no issues

**Comment by okjintao** [comment]
https://etherscan.io/tx/0x10e90db6604e445cf313269da9ceb4ad2415b3ab8e61030019421efa63cf1a7e

tesed digg lp via UI no issues

**Comment by okjintao** [comment]
@Tritium-VLK @krypt0bi will need to close this one unless someone can repro

**Comment by okjintao** [comment]
https://etherscan.io/tx/0x93a346061e0f8bcd06acf25b4b142248c7deb9080b6500b7174d41e7aa9e8643

sorry, previous tx was the approval

**Comment by sajanrajdev** [comment]
Testing with MM on Chrome

Tested graviAURA withdrawal and deposit via UI:
https://etherscan.io/tx/0x335517c517e951e95d9b62e7313d10cc55bd9507c2ad01f0704c9b344fe5e545
https://etherscan.io/tx/0xb3c7f042216061223935069abfa7769e1a8654b765b27957e462404691a8d435

Tested wBTC/DIGG/graviAURA withdrawal and deposit via UI:
https://etherscan.io/tx/0xde610566922fb7a2ed4bf2fff0ede7877195663c9ef8e48c59a7e9eeafe90f34
https://etherscan.io/tx/0xed1a5ccedc2509fe90819c1ae14c040a6229dc41b8b715a427e00c17fb4b21d8

Couldn't replicate, no issues

**Comment by okjintao** [comment]
https://github.com/Badger-Finance/badger-sdk/pull/236

found the issue, had to do with a user not being on the guest list and the sdk suppressing errors

**Comment by okjintao** [comment]
user confirmed issue is resolved
