### ISSUE TITLE
Yields do not take fees into account

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/bug-reports#5]
On the digg sett, we should pay 20% less than AURA on emitted tokens.
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/11885129/182587469-d5617ab5-0ec5-4181-a998-e5b284a2cb58.png">

Also the swap fee seems too high on the badger page.  Note conversations in discord about the subgraph being wrong.  Recommend to either use the same math as balancer and aura, or to remove swap fees and include a note that they have been excluded and why.

**Comment by dapp-whisperer** [comment]
## Key Questions
- is this worth changing, from a product perspective?
- what would the workload required be to change it?

## Tech Team Responses

### should APY take fees into account?
this is a product decision, both are simple

### swap fee discrepency
it would be a significant lift right now to dig into this, and would slow down other initiatives.

**Comment by Tritium-VLK** [comment]
https://github.com/Badger-Finance/badger-api/pull/1392

**Comment by okjintao** [comment]
release fix
