### ISSUE TITLE
review: beta app rc0

### ISSUE THREAD

**Issue by okjintao** [Badger-Finance/bug-reports#6]
# Summary

- leave bug reports / feedback on current beta here
- current state is rc0

**Comment by Tritium-VLK** [comment]
LP fees still look wildly different between badger/balancer. I don't know which one is right, but if we are going to show something different we should have a lot of detail written up.

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/11885129/182712917-1a8c76bf-31cf-4639-8847-f2184ed9daef.png">
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/11885129/182713089-f52165a6-b127-4c97-8294-21869dc8857f.png">
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/11885129/182713217-f78af888-20b3-417c-8a6e-13ea5392c76d.png">

**Comment by okjintao** [comment]
rc0 released
