### ISSUE TITLE
PROD:  bveCVX yield chart not showing

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/bug-reports#8]
Just after the last payout round.
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/11885129/183902503-33345bac-0e16-4236-9399-a55ca436095d.png">

In general I try to take a screenshot of this each round and share it when bveCVX performance is good/improving.

**Comment by Tritium-VLK** [comment]
Update: in Beta it looks better but round 24 data is missing
<img width="844" alt="image" src="https://user-images.githubusercontent.com/11885129/183934464-b7d96c84-5815-4f77-89e5-80049fecd5a2.png">

Note that the the bribe round has been finished and this round (August 10th is showing up in the dune dash)
https://dune.com/petrovska/Bribes-processing-(bveCVX)

Tree distros are here:
https://etherscan.io/tx/0x99cd95c4fd0c68c963142db17be61a8c2458ff6b5acda3aabe405a644adaee93#eventlog

**Comment by okjintao** [comment]
![image](https://user-images.githubusercontent.com/6101512/184008184-e8aa929e-e35d-4d95-a544-588d43c26052.png)
