### ISSUE TITLE
Incorrect Badger contribution to Boost in App (PROD & BETA)

### ISSUE THREAD

**Issue by okra-sf** [Badger-Finance/bug-reports#9]
For my wallet now, I expect to see 80% of my AURA Badger/WBTC LP value  + claimable badger.   Not holding Badger in wallet or in Rari, or elsewhere.  The value I see is way less than 80% of my value in the LP pool.  

The badger line on the boost optimizer page has been stuck for a day or so at least on PROD & Beta, and the same on both. 

Also I note that the boost shown in the CRV helper reward modal is the same as on the boost optimizer page, so the frontend is consistently incorrrect.

**Comment by treerao** [comment]
Numbers are the same as they have been in the boost optimizer page still .. and now this is true w/ beta out to prod still.

**Comment by okra-sf** [comment]
same values showing in the boost optimizer though market values are moving around

**Comment by okjintao** [comment]
user reports issue is resolved
